### ISSUE TITLE
[feature] add method to encode one sentence

### ISSUE THREAD

**Issue by Guitaricet** [VKCOM/YouTokenToMe#15]
Currently, for PyTorch Dataset you should make tokenisation like this:

```
tokens = model.encode([sentence])[0]
```

I may not be right here, but probably creating list of one element and selecting it back creates overhead which is not that significant, but can affect model performance (especially, if you have huge translation dataset).

It is possible to perform tokenisation in dataloader or collate_fn, but this is against PyTorch abstractions, thus should be avoided.

P.S.
Thank you a lot for yttm! It is a wonderful tool

**Comment by xbelonogov** [comment]
It's funny, but we already have this feature:) It's just probably undocumented.
