### ISSUE TITLE
Loading a BPE model with a wrong path kills the Jupyter kernel

### ISSUE THREAD

**Issue by warenlg** [VKCOM/YouTokenToMe#22]
Working with Jupyter notebooks, if you load a BPE model passing a wrong path, it will kill the kernel instead of returning a message error: `bpe = yttm.BPE(model="wrong/path/bpe.model")`.
Maybe an issue with the native extension that crashes with an exception.

* python `3.6.8`
* jupyter `1.0.0`
* youtokentome `1.0.1`

**Comment by xbelonogov** [comment]
You are right. We have this problem. It will be fixed soon. https://github.com/VKCOM/YouTokenToMe/pull/23
