### ISSUE TITLE
Handling line breaks

### ISSUE THREAD

**Issue by mgrankin** [VKCOM/YouTokenToMe#24]
At the moment YTTM ignores line breaks as all. It could be useful to use line breaks as a token in some cases. In SentencePiece this is handled by the ability to add user defined symbols to vocabulary + preprocessing. For instance I can replace all `\n` to `<|n|>` and then train my vocab:

> spm_train --input=./sometext.txt --model_prefix=m --vocab_size=50257 --user_defined_symbols='<|n|>'

**Comment by xbelonogov** [comment]
You actually can do exactly the same. Also replace `\n` to `<|n|>` and train the model. This new token appears a lot of time. The model will definitely learn it. The only small drawback is the model will also learn several useless substrings of  `<|n|>`.

**Comment by mgrankin** [comment]
There are chances the model will also learn lots of tokens like `<|n|>Hello`. I'd like to avoid that.

**Comment by xbelonogov** [comment]
Just add spaces around. Model doesn't learn tokens which cross word boundaries.
