### ISSUE TITLE
Import somehow fails

### ISSUE THREAD

**Issue by src-sauce** [VKCOM/YouTokenToMe#33]
When i'm tryping

~~~~Python
import youtokentome as yttm
~~~~

* numpy
* pandas
* youtokentome
* sentencepiece

are installed as requirements via 

~~~~
pip install -r requirements.txt
~~~~

within a virtual environment called <code>devenv</code> on a <code>Python3.6</code>

There is some symbol not found
~~~~
    (devenv) machine:tokenizer-learning USER$ python tokenize.py
    Traceback (most recent call last):
      File "tokenize.py", line 1, in <module>
        import youtokentome as yttm
      File "./tokenizer-learning/devenv/lib/python3.6/site-packages/youtokentome/__init__.py", line 1, in <module>
        from .youtokentome import BPE
      File "./tokenizer-learning/devenv/lib/python3.6/site-packages/youtokentome/youtokentome.py", line 4, in <module>
        import _youtokentome_cython
    ImportError: dlopen(./tokenizer-learning/devenv/lib/python3.6/site-packages/_youtokentome_cython.cpython-36m-darwin.so, 2): Symbol not found: __ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc
      Referenced from: ./tokenizer-learning/devenv/lib/python3.6/site-packages/_youtokentome_cython.cpython-36m-darwin.so
      Expected in: /usr/lib/libstdc++.6.dylib
     in ./tokenizer-learning/devenv/lib/python3.6/site-packages/_youtokentome_cython.cpython-36m-darwin.so
    (devenv) machine:tokenizer-learning USER$
~~~~

Maybe cause I'v upgraded recently to 10.15.1 Catalina?

I'd be happy for some help, since SentencePiece is causing us some issues in our project and we want to tackle these.

Edit:
~~~~
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import youtokentome as yttm
>>> x = yttm.BPE
>>> print(x)
<class 'youtokentome.youtokentome.BPE'>
~~~~

Seems to work out fine. So I'll work on that system, but maybe this is still a somewhat valuable information.

**Comment by LarsHill** [comment]
I have exactly the same issue.
Mac OS Sierra 10.12.6 and Python 3.7.
Youtokentome version 1.0.1 runs fine. The problem only occurs with the recent version 1.0.2

**Comment by xbelonogov** [comment]
We are working on this issue. 
Currently you can install `YouTokenToMe` for Mac OS from source. 
```
git clone git@github.com:VKCOM/YouTokenToMe.git
cd YouTokenToMe
CFLAGS="-stdlib=libc++" pip install .
```

**Comment by yutkin** [comment]
Fixed in https://github.com/VKCOM/YouTokenToMe/releases/tag/v1.0.3. Please, update package.

**Comment by yilmazay74** [comment]
I have youtoekntome version 1.0.6, but still getting No module named youtokentome   error message. I am sure it is installed.
And I am running a python script in the same environment. How come it cannot see the installed youtokentome module.
Is there any other workaround?  (Windows 10, python 3.7, youtokentome 1.0.6)
