### ISSUE TITLE
No module named 'Cython'

### ISSUE THREAD

**Issue by Not-White** [VKCOM/YouTokenToMe#61]
YouTokenToMe don't want to be installed:
"
(base) C:\Users\Администратор>pip install youtokentome
Collecting youtokentome
  Using cached https://files.pythonhosted.org/packages/af/25/e2f9863b78e5aef61bc0475bfac39f56197103f767e6f2e957cc67b989f2/youtokentome-1.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\836D~1\AppData\Local\Temp\pip-install-0wpfct7j\youtokentome\setup.py", line 5, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\836D~1\AppData\Local\Temp\pip-install-0wpfct7j\youtokentome\
"
Please, help!

**Comment by yutkin** [comment]
YouTokenToMe officially does not support Windows, but you can try to build it manually.

To fix your issue with Cython, install it: `pip install Cython`.

**Comment by Not-White** [comment]
Thank you!
