### ISSUE TITLE
[Question] How to learn joint bpe and vocabulary

### ISSUE THREAD

**Issue by cidrugHug8** [VKCOM/YouTokenToMe#74]
Hi there,

I've been using learn-joint-bpe-and-vocab with subword-nmt, how shold I use yttm?

```
subword-nmt learn-joint-bpe-and-vocab -i $data/train.truecased.$src $data/train.truecased.$trg \
        --write-vocabulary $base/shared_models/vocab.$src $base/shared_models/vocab.$trg \
        -s $bpe_num_operations -o $base/shared_models/$src$trg.bpe
```

To perform the same process above with yttm, is it correct to specify the following?

```
cat $data/train.truecased.$src $data/train.truecased.$trg > /tmp/train.cat
yttm bpe --data /tmp/train.cat --model $base/shared_models/$src$trg.bpe --vocab_size $bpe_num_operations
yttm vocab --model $base/shared_models/$src$trg.bpe > $base/shared_models/vocab.$src
cp $base/shared_models/vocab.$src $base/shared_models/vocab.$trg
```
Thank you.

**Comment by bricksdont** [comment]
Even though you are learning a joint BPE model, the vocab files `$base/shared_models/vocab.$src` and `$base/shared_models/vocab.$trg` are not the same. When a learnt BPE model is later applied to data (in your case truecased) a language-specific vocabulary file can be used together with `--vocabulary-threshold`.

This means that using the same vocab file for the source and target language (as you are doing in the yttm example above) does not lead to the same result.

**Comment by cidrugHug8** [comment]
Well, I gaave up using of yttm.
Thank you.
