### ISSUE TITLE
Installation error using pip

### ISSUE THREAD

**Issue by azayz** [VKCOM/YouTokenToMe#90]
I'm getting the following error when I try to install youtokentome 1.0.6 on AWS SageMaker, Cython is installed and it worked on AWS EC2 instance

<img width="1064" alt="Screen Shot 2021-09-07 at 5 13 20 PM" src="https://user-images.githubusercontent.com/40893766/132377830-98ae25ac-6274-40aa-9669-c691cd078ff0.png">

**Comment by geert56** [comment]
Same for me on CentOS 6.10 using g++ 4.8.2. A pity.

**Comment by otnjon** [comment]
same error here. was able to install with 
conda install -c conda-forge youtokentome

**Comment by yhfwww** [comment]
@tobitus good!
